$kind: http-request
name: application resubmitted sucessfully
description: ""
url: http://localhost:8080/applications/1/resubmit
method: PUT
body:
  type: json
  content: "{\r\n    \"area\":\"rural\"\r\n}"
auth:
  type: bearer
  credentials:
    token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI4NDg4ODg4ODg4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc4NTU4MDUyNSwiZXhwIjoxNzg1NjY2OTI1fQ.hiAjxGtyp4taMFSt3Irz3lHLJjLVidLj5hMGAAF4Eg9NsAgndRBlGuecDIUfi9ao
order: 4503599624001637
