$kind: http-request
name: Application is not awiting field review and apporved
description: ""
url: http://localhost:8080/applications/1/field-approve?remarks=Verified on site
method: PATCH
queryParams:
  remarks: Verified on site
body:
  type: json
  content: ""
auth:
  type: bearer
  credentials:
    token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5MDAwMDAwMDAxIiwicm9sZSI6IlJPTEVfRlJPTlRfREVTS19PRkZJQ0VSIiwiaWF0IjoxNzg1NTg4MTEyLCJleHAiOjE3ODU2NzQ1MTJ9.jgcmV30Rc_7pyV_rVyvLyz2WANIVJJg2ZOD0DwnQYgKhlIyQnWTUMIStivKdiP7c
order: 4503599626440452
