$kind: http-request
name: assign officer to the application
description: ""
url: http://localhost:8080/applications/3/assign?officerId=9
method: PATCH
queryParams:
  officerId: "9"
body:
  type: json
  content: ""
auth:
  type: bearer
  credentials:
    token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI5OTk5OTk5OTk5Iiwicm9sZSI6IlJPTEVfU1VQRVJfQURNSU4iLCJpYXQiOjE3ODU1NzY2NDIsImV4cCI6MTc4NTY2MzA0Mn0.4JTuv7qVbJdEFO8K-ImP0QZhqqqQP9p9hUz4JItmAAVz_OQ9_2zG6vXmHQGup7Mr
order: 4503599624515202
