$kind: http-request
name: view application by id
description: ""
url: http://localhost:8080/applications/1
method: GET
auth:
  type: bearer
  credentials:
    token: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiI4NDg4ODg4ODg4Iiwicm9sZSI6IlJPTEVfVVNFUiIsImlhdCI6MTc4NTU4MDUyNSwiZXhwIjoxNzg1NjY2OTI1fQ.hiAjxGtyp4taMFSt3Irz3lHLJjLVidLj5hMGAAF4Eg9NsAgndRBlGuecDIUfi9ao
order: 4503599588157991
