$kind: http-example
request:
  url: http://localhost:8080/applications/submit?beneficiaryId=999&schemeId=1
  method: POST
  queryParams:
    beneficiaryId: "999"
    schemeId: "1"
  body:
    type: json
    content: "{\r\n    \"income\": 500000\r\n}"
response:
  statusCode: 200
  statusText: ""
  headers:
    vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
    x-content-type-options: nosniff
    x-xss-protection: "0"
    cache-control: no-cache, no-store, max-age=0, must-revalidate
    pragma: no-cache
    expires: "0"
    x-frame-options: DENY
    content-type: text/plain;charset=UTF-8
    content-length: "21"
    date: Sat, 25 Jul 2026 05:39:20 GMT
    keep-alive: timeout=60
    connection: keep-alive
  body:
    type: text
    content: Beneficiary not found
order: 1784957966875
